# Numerical and Categorical Data Using the Tips Dataset
# We will use Seaborn’s built-in tips dataset to practice identifying numerical, categorical, discrete, continuous, nominal, and ordinal data. Because classifying columns by their meaning is more useful than blindly trusting their data types, this exercise includes both inspection and interpretation.

# Complete the following tasks using Python, Pandas, and Seaborn.

In [3]:
import seaborn as sns

data = sns.load_dataset('tips')
df = data

print(data)

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

# QUES 1 .Display the first five rows.

In [4]:
data.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

# QUES 2 . Check the data types of all columns using df.dtypes.

In [6]:
data.dtypes

total_bill     float64
tip            float64
sex           category
smoker        category
day           category
time          category
size             int64
dtype: object

# QUES3 . Filter customers whose total_bill is greater than 20

In [10]:
data[data["total_bill"] > 20]

     total_bill   tip     sex smoker  day    time  size
2         21.01  3.50    Male     No  Sun  Dinner     3
3         23.68  3.31    Male     No  Sun  Dinner     2
4         24.59  3.61  Female     No  Sun  Dinner     4
5         25.29  4.71    Male     No  Sun  Dinner     4
7         26.88  3.12    Male     No  Sun  Dinner     4
..          ...   ...     ...    ...  ...     ...   ...
237       32.83  1.17    Male    Yes  Sat  Dinner     2
238       35.83  4.67  Female     No  Sat  Dinner     3
239       29.03  5.92    Male     No  Sat  Dinner     3
240       27.18  2.00  Female    Yes  Sat  Dinner     2
241       22.67  2.00    Male    Yes  Sat  Dinner     2

[97 rows x 7 columns]

# QUES 4 . Explain why size is numerical but day is categorical

# ANSWER : -   
#  SIZE :- The size column represents the number of people sitting at a table.
#          It contains numerical values such as 1, 2, 3, and 4.

#  DAY : - The day column represents the day when a customer visited the   restaurant.
#         It contains values such as Thursday, Friday, Saturday, and Sunday.