# QUES 1 .  Student Performance DataFrame: Construction and Analysis

In [2]:
import pandas as pd
import numpy as np

In [3]:
data = {"Student_id" : [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112] ,
        "Name" : ["Amit", "Priya", "Rahul", "Neha","Vikas", "Pooja", "Karan", "Simran","Arjun", "Meena", "Rohit", "Anjali"] ,
       "Age" : [ 19, 20, 18, 21, 20, 19,22, 18, 21, 20, 19, 22 ] ,
       "Hours_Studied": [2, 5, 3, 8, 6, 4,9, 2, 7, 5, 6, 8] ,
        "Attendance": [65, 85, 70, 95, 88, 75,98, 60, 90, 82, 86, 94] ,
        "Marks": [ 48, 78, 55, 92, 84, 67,96, 45, 89, 76, 81, 93]}
df = pd.DataFrame(data)
print(df)

    Student_id    Name  Age  Hours_Studied  Attendance  Marks
0          101    Amit   19              2          65     48
1          102   Priya   20              5          85     78
2          103   Rahul   18              3          70     55
3          104    Neha   21              8          95     92
4          105   Vikas   20              6          88     84
5          106   Pooja   19              4          75     67
6          107   Karan   22              9          98     96
7          108  Simran   18              2          60     45
8          109   Arjun   21              7          90     89
9          110   Meena   20              5          82     76
10         111   Rohit   19              6          86     81
11         112  Anjali   22              8          94     93

# ques 1 . Create a DataFrame and display its first five and last three records.

In [4]:
df.head()    #HEAD USE FOR  DISPLAY FIRST 5

   Student_id   Name  Age  Hours_Studied  Attendance  Marks
0         101   Amit   19              2          65     48
1         102  Priya   20              5          85     78
2         103  Rahul   18              3          70     55
3         104   Neha   21              8          95     92
4         105  Vikas   20              6          88     84

In [5]:
df.tail(3)    #TAIL USE FOR DISPLAY LAST THREE

    Student_id    Name  Age  Hours_Studied  Attendance  Marks
9          110   Meena   20              5          82     76
10         111   Rohit   19              6          86     81
11         112  Anjali   22              8          94     93

# QUES2 .Determine the number of rows and columns programmatically. Verify that the result matches the expected dimensions

In [6]:
df.shape

(12, 6)

In [7]:
df

    Student_id    Name  Age  Hours_Studied  Attendance  Marks
0          101    Amit   19              2          65     48
1          102   Priya   20              5          85     78
2          103   Rahul   18              3          70     55
3          104    Neha   21              8          95     92
4          105   Vikas   20              6          88     84
5          106   Pooja   19              4          75     67
6          107   Karan   22              9          98     96
7          108  Simran   18              2          60     45
8          109   Arjun   21              7          90     89
9          110   Meena   20              5          82     76
10         111   Rohit   19              6          86     81
11         112  Anjali   22              8          94     93

# ques3 . Extract all column names as a Python list and classify them as identifiers, categorical attributes, or numerical attributes.

In [13]:
columns = df.columns.tolist()
print(columns)

identifers = ["Student_id" , "Name"]
categorical_attributes = ["Name"]
numerical_attributes = ["Student_id" , "Age" , "Hours_studied" , "Attendance" , "Marks"]


print(identifers)
print(categorical_attributes)
print(numerical_attributes)

['Student_id', 'Name', 'Age', 'Hours_Studied', 'Attendance', 'Marks']
['Student_id', 'Name']
['Name']
['Student_id', 'Age', 'Hours_studied', 'Attendance', 'Marks']

# ques 4 . Select the Name, Hours_Studied, and Marks columns. Then identify students whose marks are above the dataset's average.

In [14]:
df

    Student_id    Name  Age  Hours_Studied  Attendance  Marks
0          101    Amit   19              2          65     48
1          102   Priya   20              5          85     78
2          103   Rahul   18              3          70     55
3          104    Neha   21              8          95     92
4          105   Vikas   20              6          88     84
5          106   Pooja   19              4          75     67
6          107   Karan   22              9          98     96
7          108  Simran   18              2          60     45
8          109   Arjun   21              7          90     89
9          110   Meena   20              5          82     76
10         111   Rohit   19              6          86     81
11         112  Anjali   22              8          94     93

In [15]:
# Select columns
print(df[["Name", "Hours_Studied", "Marks"]])

      Name  Hours_Studied  Marks
0     Amit              2     48
1    Priya              5     78
2    Rahul              3     55
3     Neha              8     92
4    Vikas              6     84
5    Pooja              4     67
6    Karan              9     96
7   Simran              2     45
8    Arjun              7     89
9    Meena              5     76
10   Rohit              6     81
11  Anjali              8     93

In [16]:
avg = df["Marks"].mean()

In [17]:
print(avg)

75.33333333333333

# ques 4 . Reset the index after filtering, compare the original and new indices, and explain why an index should not automatically be treated as a student's unique identifier.

# MAIN_QUES 2 . Advanced Row and Column Selection Using iloc and loc

In [18]:
df

    Student_id    Name  Age  Hours_Studied  Attendance  Marks
0          101    Amit   19              2          65     48
1          102   Priya   20              5          85     78
2          103   Rahul   18              3          70     55
3          104    Neha   21              8          95     92
4          105   Vikas   20              6          88     84
5          106   Pooja   19              4          75     67
6          107   Karan   22              9          98     96
7          108  Simran   18              2          60     45
8          109   Arjun   21              7          90     89
9          110   Meena   20              5          82     76
10         111   Rohit   19              6          86     81
11         112  Anjali   22              8          94     93

# QUES 1 . Select rows at positions 2 through 7 using iloc, returning only Name, Attendance, and Marks. Explain why the ending position behaves differently from the equivalent label-based selection.

In [19]:
result = df.iloc[2:8][["Name" , "Attendance" , "Marks"]]
print(result)

     Name  Attendance  Marks
2   Rahul          70     55
3    Neha          95     92
4   Vikas          88     84
5   Pooja          75     67
6   Karan          98     96
7  Simran          60     45

# ques2 .Create a copy of the DataFrame and set Student_ID as its index. Use loc to retrieve students with IDs 103, 107, and 110.

In [20]:
df2 = df.copy()
df2 = df2.set_index("Student_id")
result = df2.loc[[103 , 107 , 110]]
print(result)

             Name  Age  Hours_Studied  Attendance  Marks
Student_id
103         Rahul   18              3          70     55
107         Karan   22              9          98     96
110         Meena   20              5          82     76

# without copy we can find like this

In [21]:
df = df.set_index("Student_id")

print(df.loc[[103, 107, 110]])

             Name  Age  Hours_Studied  Attendance  Marks
Student_id
103         Rahul   18              3          70     55
107         Karan   22              9          98     96
110         Meena   20              5          82     76

# ques 3 . Using Boolean conditions, identify students who studied at least 6 hours, have attendance of at least 85%, and scored more than 80 marks.

In [23]:
result = df[
    (df["Hours_Studied"] >= 6) &
    (df["Attendance"] >= 85) &
    (df["Marks"] > 80)
]

print(result)

              Name  Age  Hours_Studied  Attendance  Marks
Student_id
104           Neha   21              8          95     92
105          Vikas   20              6          88     84
107          Karan   22              9          98     96
109          Arjun   21              7          90     89
111          Rohit   19              6          86     81
112         Anjali   22              8          94     93

In [24]:
df

              Name  Age  Hours_Studied  Attendance  Marks
Student_id
101           Amit   19              2          65     48
102          Priya   20              5          85     78
103          Rahul   18              3          70     55
104           Neha   21              8          95     92
105          Vikas   20              6          88     84
106          Pooja   19              4          75     67
107          Karan   22              9          98     96
108         Simran   18              2          60     45
109          Arjun   21              7          90     89
110          Meena   20              5          82     76
111          Rohit   19              6          86     81
112         Anjali   22              8          94     93

## ques 4 .Using iloc, extract the last four students and the last three columns without writing any column names explicitly.

In [31]:
result = df.iloc[-4 :, -3 :]
print(result)

            Hours_Studied  Attendance  Marks
Student_id
109                     7          90     89
110                     5          82     76
111                     6          86     81
112                     8          94     93

#ques 5 Create a new DataFrame containing students whose marks are below the median. Preserve their original student IDs and explain why filtering rows and resetting the index can produce different index labels.

In [32]:
median_marks = df["Marks"].median()
df2 = df[df["Marks"] < median_marks]
print(df2)

              Name  Age  Hours_Studied  Attendance  Marks
Student_id
101           Amit   19              2          65     48
102          Priya   20              5          85     78
103          Rahul   18              3          70     55
106          Pooja   19              4          75     67
108         Simran   18              2          60     45
110          Meena   20              5          82     76

In [34]:
import pandas as pd

df = pd.DataFrame({
    "Student_ID": [201, 202, 203, 204, 205, 206, 207, 208, 209, 210],

    "Hours_Studied": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],

    "Attendance": [50, 55, 60, 65, 70, 75, 80, 85, 90, 95],

    "Sleep_Hours": [8, 7, 8, 6, 7, 6, 7, 8, 6, 7],

    "Marks": [35, 40, 48, 52, 61, 68, 74, 82, 90, 96]
})

print(df)

   Student_ID  Hours_Studied  Attendance  Sleep_Hours  Marks
0         201              1          50            8     35
1         202              2          55            7     40
2         203              3          60            8     48
3         204              4          65            6     52
4         205              5          70            7     61
5         206              6          75            6     68
6         207              7          80            7     74
7         208              8          85            8     82
8         209              9          90            6     90
9         210             10          95            7     96

# QUES1 . Create X_single using only Hours_Studied and y using Marks. Demonstrate the difference between selecting the feature with single and double square brackets using type(), shape, and the resulting structure.

In [40]:
x_single = df[["Hours_Studied"]]
y = df["Marks"]

print(x_single)
print(y)
print(type(x_single))
print(x_single.shape)

   Hours_Studied
0              1
1              2
2              3
3              4
4              5
5              6
6              7
7              8
8              9
9             10
0    35
1    40
2    48
3    52
4    61
5    68
6    74
7    82
8    90
9    96
Name: Marks, dtype: int64
<class 'pandas.core.frame.DataFrame'>
(10, 1)

# df["Marks"]                    # Series
# df[["Marks"]]                  # DataFrame
# df[["Marks", "Attendance"]]    # DataFrame with 2 columns

# ques2 . Create X_multi using Hours_Studied, Attendance, and Sleep_Hours. Verify that Marks and Student_ID are excluded from the feature set.

In [49]:
x_multi = df[["Hours_Studied" , "Attendance" , "Sleep_Hours"]]
print(x_multi)
print(x_multi.columns.tolist())
print(x_multi.shape)
print("Marks" not in x_multi.columns)
print("Student_ID" not in x_multi.columns)

   Hours_Studied  Attendance  Sleep_Hours
0              1          50            8
1              2          55            7
2              3          60            8
3              4          65            6
4              5          70            7
5              6          75            6
6              7          80            7
7              8          85            8
8              9          90            6
9             10          95            7
['Hours_Studied', 'Attendance', 'Sleep_Hours']
(10, 3)
True
True

# QUES 3. Use drop() to construct features and target variables. Verify programmatically that no target column remains in X.

In [50]:

X = df.drop(columns=["Student_ID", "Marks"])
y = df["Marks"]

print( X.columns.tolist())
print( y.name)
print("Marks" not in X.columns)

['Hours_Studied', 'Attendance', 'Sleep_Hours']
Marks
True

# QUES4 . Write validation code that checks whether X and y contain the same number of observations, whether X has the intended number of features, and whether the target is one-dimensional.

In [51]:
X = df.drop(columns=["Student_ID", "Marks"])
y = df["Marks"]

assert X.shape[0] == y.shape[0], "Rows do not match"
assert X.shape[1] == 3, "Expected 3 features"                                     # Ab assert kya hai?
                                                                                  # assert ka matlab hai kisi condition ko check karna.
                                                                                  # Condition True hai → code aage chalega.
                                                                                  # Condition False hai → AssertionError aayega aur saath mein diya message dikhega.
assert y.ndim == 1, "Target must be one-dimensional"

print("All validations passed!")

All validations passed!

# QUES 5 . xplain why including Student_ID as a predictive feature may be inappropriate, even though it contains numerical values. Support your explanation with a comparison of the feature sets.

ANSWER :- `Student_ID` contains numerical values, but it is an identifier used to identify students, not a meaningful measure of their academic performance. Including it as a predictive feature may cause the model to learn misleading patterns and reduce its ability to generalize to new students.

With `Student_ID`, the feature set contains four columns: `Student_ID`, `Hours_Studied`, `Attendance`, and `Sleep_Hours`, with shape `(10, 4)`.

After excluding `Student_ID`, the feature set contains three columns: `Hours_Studied`, `Attendance`, and `Sleep_Hours`, with shape `(10, 3)`.

Therefore, `Student_ID` is excluded because the other three features provide more meaningful information for predicting `Marks`.

# END TO END DATA PREPRETION CHALLENGE ?

In [67]:

import pandas as pd

df = pd.DataFrame({
    "Student_ID": range(401, 421),
    "Name": [
        "A", "B", "C", "D", "E", "F", "G", "H", "I", "J",
        "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T"
    ],
    "Hours_Studied": [
        1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
        2, 4, 6, 8, 3, 5, 7, 9, 1, 10
    ],
    "Attendance": [
        50, 55, 60, 65, 70, 75, 80, 85, 90, 95,
        58, 67, 78, 88, 62, 73, 83, 92, 52, 98
    ],
    "Sleep_Hours": [
        5, 6, 7, 8, 6, 7, 8, 5, 6, 7,
        8, 5, 6, 7, 8, 6, 7, 5, 6, 8
    ],
    "Final_Marks": [
        30, 38, 45, 52, 60, 67, 75, 83, 90, 98,
        40, 54, 70, 87, 48, 63, 78, 92, 34, 96
    ]
})

print(df)
print("Shape:", df.shape)
print("Columns:", df.columns.tolist())

    Student_ID Name  Hours_Studied  Attendance  Sleep_Hours  Final_Marks
0          401    A              1          50            5           30
1          402    B              2          55            6           38
2          403    C              3          60            7           45
3          404    D              4          65            8           52
4          405    E              5          70            6           60
5          406    F              6          75            7           67
6          407    G              7          80            8           75
7          408    H              8          85            5           83
8          409    I              9          90            6           90
9          410    J             10          95            7           98
10         411    K              2          58            8           40
11         412    L              4          67            5           54
12         413    M              6          78            6           70
13         414    N              8          88            7           87
14         415    O              3          62            8           48
15         416    P              5          73            6           63
16         417    Q              7          83            7           78
17         418    R              9          92            5           92
18         419    S              1          52            6           34
19         420    T             10          98            8           96
Shape: (20, 6)
Columns: ['Student_ID', 'Name', 'Hours_Studied', 'Attendance', 'Sleep_Hours', 'Final_Marks']

# QUES 1 . Inspect the DataFrame and write a reusable function that reports the number of rows, columns, column names, data types, and missing values. The function must work with other DataFrames too.

In [68]:
import pandas as pd

def inspect_dataframe(data):
    print("Number of rows:", data.shape[0])
    print("Number of columns:", data.shape[1])

    print("\nColumn names:")
    print(data.columns.tolist())

    print("\nData types:")
    print(data.dtypes)

    print("\nMissing values in each column:")
    print(data.isnull().sum())


# Function call
inspect_dataframe(df)

Number of rows: 20
Number of columns: 6

Column names:
['Student_ID', 'Name', 'Hours_Studied', 'Attendance', 'Sleep_Hours', 'Final_Marks']

Data types:
Student_ID        int64
Name             object
Hours_Studied     int64
Attendance        int64
Sleep_Hours       int64
Final_Marks       int64
dtype: object

Missing values in each column:
Student_ID       0
Name             0
Hours_Studied    0
Attendance       0
Sleep_Hours      0
Final_Marks      0
dtype: int64

In [69]:
data = {
    "Name" : ["ADITYA" , "RAJEEV" , "AYUSH"] ,
    "ROLL_NO" : [4 , 6 , 7] ,
    "ID" : [11, 121 ,102]
}

df1 = pd.DataFrame(data)
print(df1)

     Name  ROLL_NO   ID
0  ADITYA        4   11
1  RAJEEV        6  121
2   AYUSH        7  102

In [70]:
inspect_dataframe(df1)

Number of rows: 3
Number of columns: 3

Column names:
['Name', 'ROLL_NO', 'ID']

Data types:
Name       object
ROLL_NO     int64
ID          int64
dtype: object

Missing values in each column:
Name       0
ROLL_NO    0
ID         0
dtype: int64

# QUES2 . Build two feature sets: one using only Hours_Studied, and another using Hours_Studied, Attendance, and Sleep_Hours. Use Final_Marks as the target in both cases. Compare their dimensions and explain the difference between single-feature and multi-feature learning.

# SINGLE FEATURE : - A machine learning method that uses only one input feature to predict the target.

In [71]:
df

    Student_ID Name  Hours_Studied  Attendance  Sleep_Hours  Final_Marks
0          401    A              1          50            5           30
1          402    B              2          55            6           38
2          403    C              3          60            7           45
3          404    D              4          65            8           52
4          405    E              5          70            6           60
5          406    F              6          75            7           67
6          407    G              7          80            8           75
7          408    H              8          85            5           83
8          409    I              9          90            6           90
9          410    J             10          95            7           98
10         411    K              2          58            8           40
11         412    L              4          67            5           54
12         413    M              6          78            6           70
13         414    N              8          88            7           87
14         415    O              3          62            8           48
15         416    P              5          73            6           63
16         417    Q              7          83            7           78
17         418    R              9          92            5           92
18         419    S              1          52            6           34
19         420    T             10          98            8           96

In [72]:
X1 = df[["Hours_Studied"]]
y = df["Final_Marks"]

print("X1 dimensions:", X1.shape)
print("y dimensions:", y.shape)

X1 dimensions: (20, 1)
y dimensions: (20,)

# MULTI FEATURE : - A machine learning method that uses two or more input features to predict the target.

In [73]:
X2 = df[["Hours_Studied", "Attendance", "Sleep_Hours"]]
y = df["Final_Marks"]

print("X2 dimensions:", X2.shape)
print("y dimensions:", y.shape)

X2 dimensions: (20, 3)
y dimensions: (20,)

# QUES3 . Filter students with attendance below 70, then select their names, IDs, and marks. Preserve the student IDs after filtering and explain how the index differs from the ID.

In [74]:
result = df[df["Attendance"] <= 70] [["Name" , "Student_ID" , "Final_Marks"]]
print(result)

   Name  Student_ID  Final_Marks
0     A         401           30
1     B         402           38
2     C         403           45
3     D         404           52
4     E         405           60
10    K         411           40
11    L         412           54
14    O         415           48
18    S         419           34

# QUES4 . Create a reproducible 20% test split for the multi-feature dataset. Verify that the training and testing indices do not overlap and that all four outputs have consistent dimensions.